import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "./_components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="mx-auto max-w-6xl">
          <Header />
          <div className="mt-5">{children}</div>
        </main>
      </body>
    </html>
  );
}
